# Generated by Django 4.2.8 on 2024-02-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_tipos_efivika_remove_tipos_egkyklopaidies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='selides',
        ),
        migrations.RemoveField(
            model_name='book',
            name='urlamazon',
        ),
        migrations.RemoveField(
            model_name='book',
            name='vathmologia',
        ),
        migrations.RemoveField(
            model_name='syggrafeas',
            name='c_v',
        ),
        migrations.RemoveField(
            model_name='syggrafeas',
            name='hm_gen',
        ),
    ]
