# Generated by Django 4.2.8 on 2024-02-08 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ekdotikos_oikos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('diefth', models.CharField(max_length=300, null=True)),
                ('thl', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='syggrafeas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hm_gen', models.CharField(max_length=300, null=True)),
                ('c_v', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sxolika', models.CharField(max_length=100)),
                ('ksenoglossa', models.CharField(max_length=300, null=True)),
                ('logotexnika', models.CharField(max_length=300, null=True)),
                ('epistimes', models.CharField(max_length=300, null=True)),
                ('paidika', models.CharField(max_length=300, null=True)),
                ('efivika', models.CharField(max_length=300, null=True)),
                ('leksika', models.CharField(max_length=300, null=True)),
                ('egkyklopaidies', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlos', models.CharField(max_length=50)),
                ('selides', models.CharField(max_length=300, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('urlamazon', models.TextField(null=True)),
                ('vathmologia', models.TextField(null=True)),
                ('perilipsi', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('timi', models.TextField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ekdotikos_oikos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ekdotikos_oikos')),
                ('syggrafeas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.syggrafeas')),
                ('tipos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.tipos')),
            ],
        ),
    ]
