# Generated by Django 4.2.8 on 2024-02-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipos',
            name='efivika',
        ),
        migrations.RemoveField(
            model_name='tipos',
            name='egkyklopaidies',
        ),
        migrations.RemoveField(
            model_name='tipos',
            name='epistimes',
        ),
        migrations.RemoveField(
            model_name='tipos',
            name='ksenoglossa',
        ),
        migrations.RemoveField(
            model_name='tipos',
            name='leksika',
        ),
        migrations.RemoveField(
            model_name='tipos',
            name='logotexnika',
        ),
        migrations.RemoveField(
            model_name='tipos',
            name='paidika',
        ),
        migrations.RemoveField(
            model_name='tipos',
            name='sxolika',
        ),
        migrations.AddField(
            model_name='tipos',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
