# Generated by Django 4.2.8 on 2024-02-08 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_book_selides_remove_book_urlamazon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekdotikos_oikos',
            name='diefth',
        ),
        migrations.RemoveField(
            model_name='ekdotikos_oikos',
            name='thl',
        ),
    ]
